apiVersion: apps/v1
kind: Deployment
metadata:
  name: process-service
  namespace: supplychainx
  labels:
    app: process-service
    app.kubernetes.io/part-of: supplychainx
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: process-service
  template:
    metadata:
      labels:
        app: process-service
        app.kubernetes.io/part-of: supplychainx
    spec:
      terminationGracePeriodSeconds: 40
      containers:
        - name: process-service
          image: supplychainx-process-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
              name: http
          envFrom:
            - configMapRef:
                name: supplychainx-config
            - secretRef:
                name: supplychainx-secrets
          env:
            - name: DB_HOST
              value: "postgres"
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: "supplychainx_db"
            - name: DB_USERNAME
              value: "postgres"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: supplychainx-secrets
                  key: POSTGRES_PASSWORD
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "kafka:9092"
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: supplychainx-secrets
                  key: Jwt__SecretKey
            - name: JWT_ISSUER
              value: "SupplyChainX"
            - name: JWT_AUDIENCE
              value: "SupplyChainXClients"
          resources:
            requests:
              cpu: 150m
              memory: 256Mi
            limits:
              cpu: 750m
              memory: 512Mi
          startupProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8081
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 12
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8081
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8081
            initialDelaySeconds: 20
            periodSeconds: 10
            failureThreshold: 3
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
---
apiVersion: v1
kind: Service
metadata:
  name: process-service
  namespace: supplychainx
  labels:
    app: process-service
    app.kubernetes.io/part-of: supplychainx
spec:
  type: ClusterIP
  ports:
    - port: 8081
      targetPort: 8081
      name: http
  selector:
    app: process-service
