apiVersion: v1
kind: Secret
metadata:
  name: supplychainx-secrets
  namespace: supplychainx
  labels:
    app.kubernetes.io/part-of: supplychainx
type: Opaque
stringData:
  POSTGRES_PASSWORD: "postgres_dev_password"
  POSTGRES_CONNECTION_STRING: "Host=postgres;Port=5432;Database=supplychainx_db;Username=postgres;Password=postgres_dev_password"
  ConnectionStrings__DefaultConnection: "Host=postgres;Port=5432;Database=supplychainx_db;Username=postgres;Password=postgres_dev_password"
  Jwt__SecretKey: "SupplyChainX_ProductionGrade_SecretKey_2026_Minimum32Bytes!"
  AiCopilot__OpenAiApiKey: ""
  AiCopilot__AzureOpenAiApiKey: ""

