server:
  port: 0
  shutdown: graceful

spring:
  application:
    name: process-service-test
  lifecycle:
    timeout-per-shutdown-phase: 30s

  datasource:
    url: jdbc:h2:mem:process_service_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=PostgreSQL
    username: sa
    password: 
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect

jwt:
  secret: SupplyChainX_Super_Secret_Jwt_Signing_Key_2026_Enterprise_Secure!
  issuer: SupplyChainX
  audience: SupplyChainXClients

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  health:
    probes:
      enabled: true

logging:
  level:
    root: INFO
    com.supplychainx.processservice: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} [service=process-service, correlationId=%X{correlationId:-none}, processId=%X{processId:-none}, eventId=%X{eventId:-none}] - %msg%n"

