server:
  port: ${PORT:8081}

spring:
  application:
    name: process-service

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:supplychainx_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres_dev_password}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO:update}
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: ${KAFKA_PROCESS_GROUP_ID:supplychainx-process-analytics-group}
      auto-offset-reset: earliest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    listener:
      ack-mode: manual_immediate

process:
  kafka:
    topics:
      product-events: ${KAFKA_TOPIC_PRODUCT:supplychainx.product.events}
      warehouse-events: ${KAFKA_TOPIC_WAREHOUSE:supplychainx.warehouse.events}
      inventory-events: ${KAFKA_TOPIC_INVENTORY:supplychainx.inventory.events}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
